config/routes.rb
Rails.application.routes.draw do
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    get '/',                        to: 'home#index'
    get 'index',                    to: 'home#index'
    get 'products/search',          to: 'products#search'
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :single_product,            to: 'sample#single_product'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
    resources :products, only: [:show]
    resources :categories, only: [:show]
    post 'products/search', to: 'products#search'
    get 'cart',                     to: 'orders#edit'
    patch 'cart',                   to: 'orders#update'
    resources :line_items, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/potepan/option_value_decorator.rb
module Potepan::OptionValueDecorator
  Spree::OptionValue.class_eval do
    scope :values_all, -> (value) { includes(:option_type).where(spree_option_types: { presentation: value }) }
  end
end

app/models/potepan/product_decorator.rb
module Potepan::ProductDecorator
  Spree::Product.class_eval do
    def related_products
      Spree::Product.in_taxons(taxons).where.not(id: id).distinct
    end
    scope :filter_by_color, -> (color) { joins(variants: :option_values).where(potepan_option_values: { name: color }).distinct }
    scope :filter_by_size, -> (size) { joins(variants: :option_values).where(potepan_option_values: { name: size }).distinct }

    scope :from_high_price_to_low_price, -> { unscope(:order).descend_by_master_price }
    scope :from_low_price_to_high_price, -> { unscope(:order).ascend_by_master_price }
    scope :from_newest_to_oldest, -> { reorder(available_on: :desc) }
    scope :from_oldest_to_newest, -> { reorder(available_on: :asc) }

    scope :sort_in_order, -> (sort) do
      case sort
      when "NEW_PRODUCTS"
        from_newest_to_oldest
      when "OLD_PRODUCTS"
        from_oldest_to_newest
      when "LOW_PRICE"
        from_low_price_to_high_price
      when "HIGH_PRICE"
        from_high_price_to_low_price
      end
    end
  end
  Spree::Product.prepend self
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/potepan/categories_controller.rb
class Potepan::CategoriesController < ApplicationController
  helper_method :count_number_of_products_by_option
  def show
    @categories = Spree::Taxonomy.all.includes(:taxons)
    @taxon = Spree::Taxon.find(params[:id])
    @products = @taxon.all_products.includes(master: [:images, :default_price]).from_newest_to_oldest.sort_in_order(params[:sort])
    @colors = Spree::OptionValue.values_all("Color")
    @sizes = Spree::OptionValue.values_all("Size")
    @sorts = Spree::OptionValue.values_all("Sort")
  end

  def filter_params
    { color: params[:color], size: params[:size], sort: params[:sort] }
  end

  def count_number_of_products_by_option(option_value)
    @taxon.all_products.includes(variants: :option_values).where(spree_option_values: { name: option_value.name }).count
  end
end

app/controllers/potepan/home_controller.rb
class Potepan::HomeController < ApplicationController
  MAX_NUMBER_OF_NEW_PRODUCTS = 8

  def index
    @new_products = Spree::Product.includes(master: [:default_price, :images]).
      order(available_on: :desc).
      limit(MAX_NUMBER_OF_NEW_PRODUCTS).
      from_newest_to_oldest
  end
end

app/controllers/potepan/line_items_controller.rb
class Potepan::LineItemsController < ApplicationController
  protect_from_forgery
  include Spree::Core::ControllerHelpers::Order
  include Spree::Core::ControllerHelpers::Auth
  include Spree::Core::ControllerHelpers::Store

  def create
    order = current_order(create_order_if_necessary: true)
    authorize! :update, order, cookies.signed[:guest_token]

    variant = Spree::Variant.find(params[:variant_id])
    quantity = params[:quantity].to_i

    if !quantity.between?(1, 2_147_483_647)
      order.errors.add(:base, t('spree.please_enter_reasonable_quantity'))
    end

    begin
      @line_item = order.contents.add(variant, quantity)
    rescue ActiveRecord::RecordInvalid => e
      order.errors.add(:base, e.record.errors.full_messages.join(","))
    end

    if order.errors.any?
      flash[:error] = order.errors.full_messages.join(",")
      redirect_back_or_default(spree.root_path)
      return
    else
      redirect_to potepan_cart_path
    end
  end

  def destroy
    item = Spree::LineItem.find(params[:id])
    item.order.contents.remove_line_item(item)
    redirect_to potepan_cart_path
  end
end

app/controllers/potepan/orders_controller.rb
class Potepan::OrdersController < ApplicationController
  include Spree::Core::ControllerHelpers::Order
  include Spree::Core::ControllerHelpers::Auth
  include Spree::Core::ControllerHelpers::Store

  def edit
    @order = current_order || Spree::Order.incomplete.
      find_or_initialize_by(guest_token: cookies.signed[:guest_token])
  end

  def update
    @order = Spree::Order.find_by(number: params[:number])
    @order.contents.update_cart(order_params)
    redirect_to potepan_cart_path
  end

  def order_params
    params.require(:order).permit(line_items_attributes: [:id, :quantity])
  end
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  RELATED_PRODUCTS_LIMIT_MAX_NUMBER = 4
  def show
    @product = Spree::Product.find(params[:id])
    @taxons = @product.taxons
    @related_products = @product.related_products.
      includes(master: [:images, :default_price]).
      limit(RELATED_PRODUCTS_LIMIT_MAX_NUMBER)
  end

  def search
    @search_word = params[:searchWord]
    searched_products = Spree::Product.ransack(name_or_description_cont: params[:searchWord]).
      result.includes(variants_including_master: %i(images prices))
    @products = searched_products
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  def index
  end

  def product_grid_left_sidebar
  end

  def product_list_left_sidebar
  end

  def single_product
  end

  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_footer.html.erb
<!-- FOOTER -->
<!-- COPY RIGHT -->
<div id="footer" class="copyRight clearfix">
  <div class="container">
    <div class="row">
      <div class="col-sm-7 col-xs-12">
        <p>&copy; 2016-<%= Time.current.year %> Copyright Potepan Store .</p>
      </div>
      <div class="col-sm-5 col-xs-12">
        <ul class="list-inline">
          <li><a href="#"><i class="fa fa-twitter"></i></a></li>
          <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="header clearfix">
  <!-- TOPBAR -->
  <div class="topBar">
    <div class="container">
      <div class="row">
        <div class="col-md-6 hidden-sm hidden-xs">
          <ul class="list-inline">
            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
          </ul>
        </div>
        <div class="col-md-6 col-xs-12">
          <ul class="list-inline pull-right">
            <li class="dropdown searchBox">
              <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-search"></i></a>
              <ul class="dropdown-menu dropdown-menu-right">
                  <li>
                    <%= form_with url: potepan_products_search_path, id: "form01", method: :get, local: true do |form| %>
                    <span class="input-group">
                      <%= form.text_field "searchWord",id: "searchWord", class: "form-control", placeholder: "Search…", 'aria-describedby': "basic-addon2" %>
                      <button><span class="input-group-addon" id="basic-addon2">検索</span></button>
                    <% end %>
                    </span>
                  </li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="/potepan/cart" class="dropdown-toggle" data-toggle="dropdown disabled"><i class="fa fa-shopping-cart"></i></a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <!-- NAVBAR -->
  <nav class="navbar navbar-main navbar-default" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/potepan/index"><%= image_tag("img/logo.png", :alt => "") %></a>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'Home', potepan_path %></li>
          <li class="dropdown megaDropMenu active">
            <a href="/potepan/categories/1" class="dropdown-toggle">Shop</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</div>

app/views/layouts/_login_modal.html.erb
<!-- LOGIN MODAL -->
<div class="modal fade" id="login" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">log in</h3>
      </div>
      <div class="modal-body">
        <form action="" method="POST" role="form">
          <div class="form-group">
            <label for="login-email">Enter Email</label>
            <input type="email" class="form-control" id="login-email">
          </div>
          <div class="form-group">
            <label for="login-password">Password</label>
            <input type="password" class="form-control" id="login-password">
          </div>
          <div class="checkbox">
            <label>
              <input type="checkbox"> Remember Me
            </label>
          </div>
          <button type="submit" class="btn btn-primary btn-block">log in</button>
          <button type="button" class="btn btn-link btn-block">Forgot Password?</button>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_signup_modal.html.erb
<!-- SIGN UP MODAL -->
<div class="modal fade" id="signup" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">Create an account</h3>
      </div>
      <div class="modal-body">
        <form action="" method="POST" role="form">
          <div class="form-group">
            <label for="signup-email">Enter Email</label>
            <input type="email" class="form-control" id="signup-email">
          </div>
          <div class="form-group">
            <label for="signup-password">Password</label>
            <input type="password" class="form-control" id="signup-password">
          </div>
          <div class="form-group">
            <label for="signup-password-confirmation">Confirm Password</label>
            <input type="password" class="form-control" id="signup-password-confirmation">
          </div>
          <button type="submit" class="btn btn-primary btn-block">Sign up</button>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='en'>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= yield(:title).presence || "BIGBAG Store" %></title>
    <%= csrf_meta_tags %>

    <!-- GOOGLE FONT -->
    <%= stylesheet_link_tag "application", 'https://fonts.googleapis.com/css?family=Oxygen:400,300,700', :media => "all" %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <div class="main-wrapper">
      <%= render "layouts/header" %>
      <%= yield %>
      <%= render "layouts/footer" %>
      <%= render "layouts/login_modal" %>
      <%= render "layouts/signup_modal" %>
    </div>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/potepan/categories/_categories.html.erb
<div class="panel panel-default">
  <div class="panel-heading">商品カテゴリー</div>
  <div class="panel-body">
    <div class="collapse navbar-collapse navbar-ex1-collapse navbar-side-collapse">
      <% categories.each do |cat| %>
        <ul class="nav navbar-nav side-nav">
          <li>
            <a href="javascript:;" data-toggle="collapse" data-target="#<%= cat.name %>"><%= cat.name %>
              <i class="fa fa-plus"></i>
            </a>
            <ul id="<%= cat.name %>" class="collapse collapseItem">
              <% cat.root.leaves.each do |leaf| %>
                <li>
                  <%= link_to potepan_category_path(leaf.id) do %>
                    <i class="fa fa-caret-right" aria-hidden="true"></i>
                    <%= leaf.name %>
                    <span>(<%=leaf.products.count %>)</span>
                  <% end %>
                </li>
              <% end %>
            </ul>
          </li>
        </ul>
      <% end %>
    </div>
  </div>
</div>

app/views/potepan/categories/_filter_by_color.html.erb
<div class="panel panel-default filterNormal">
  <div class="panel-heading">色から探す</div>
  <div class="panel-body">
    <ul class="list-unstyled" id="filter_by_color">
      <% @colors.each do |color| %>
        <li>
          <%= link_to (potepan_category_path(id: taxon.id, color: color.name)) do %>
            <%= color.name %><span>(<%= count_number_of_products_by_option(color) %>)</span>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/potepan/categories/_filter_by_grid_or_list.html.erb
<div class="col-xs-6">
  <div class="btn-group pull-right" role="group">
    <button type="button" class="btn btn-default active" onclick="window.location.href='product_grid_left_sidebar.html'"><i class="fa fa-th" aria-hidden="true"></i><span>Grid</span></button>
    <button type="button" class="btn btn-default" onclick="window.location.href='product_list_left_sidebar.html'"><i class="fa fa-th-list" aria-hidden="true"></i><span>List</span></button>
  </div>
</div>

app/views/potepan/categories/_filter_by_size.html.erb
<div class="panel panel-default filterNormal">
  <div class="panel-heading">サイズから探す</div>
  <div class="panel-body">
    <ul class="list-unstyled clearfix">
      <% @sizes.each do |size| %>
        <li>
          <%= link_to (potepan_category_path(id: taxon.id, size: size.name)) do %>
            <%= size.presentation %><span>(<%= count_number_of_products_by_option(size) %>)</span>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/potepan/categories/_filter_by_sort.html.erb
<div class="col-xs-6">
  <%= form_tag(request.path, method: :get, enforce_utf8: false) do %>
    <%= hidden_field_tag :color, params[:color] if params[:color] %>
    <%= hidden_field_tag :size, params[:size] if params[:size] %>
    <%= select_tag "sort", options_for_select([
      ["新着順", "NEW_PRODUCTS"],
      ["安い順", "LOW_PRICE"],
      ["高い順", "HIGH_PRICE"],
      ["古い順", "OLD_PRODUCTS"]],
      selected: params[:sort] || "NEW_PRODUCTS"),
      { class: "select-drop", onchange: "this.form.submit()"} %>
  <% end %>
</div>

app/views/potepan/categories/_light_section_brands.html.erb
<section class="lightSection clearfix">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="owl-carousel partnersLogoSlider">
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-01.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-02.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-03.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-04.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-05.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-01.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-02.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-03.png", :alt => "partner-img") %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/potepan/categories/_products.html.erb
<div class="row">
  <% products.each do |product| %>
    <div class="col-sm-4 col-xs-12">
      <div class="productBox">
        <%= link_to potepan_product_path(product.id) do %>
          <div class="productImage clearfix">
            <%= image_tag(product.display_image.attachment(:small)) %>
          </div>
          <div class="productCaption clearfix">
            <h5><%= product.name %></h5>
            <h3><%= product.display_price %></h3>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/potepan/categories/show.html.erb
<% provide(:title, @taxon.name) %>
<!-- LIGHT SECTION -->
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= @taxon.name %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <%= link_to("Home", potepan_index_url ) %>
          </li>
          <li>
            <a href="#">shop</a>
          </li>
          <li class="active">
            <%= @taxon.name %>
          </li>
        </ol>
      </div>
    </div>
  </div>
</section>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix productsContent">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-4 col-xs-12 sideBar">
        <%= render 'categories',categories: @categories %>
        <%= render 'filter_by_color', colors: @colors, taxon: @taxon %>
        <%= render 'filter_by_size', sizes: @size, taxon: @taxon %>
      </div>
      <div class="col-md-9 col-sm-8 col-xs-12">
        <div class="row filterArea">
          <%= render "filter_by_sort" %>
          <%= render "filter_by_grid_or_list" %>
        </div>
        <%= render 'products', products: @products %>
      </div>
    </div>
  </div>
</section>
<!-- LIGHT SECTION -->
<%= render 'light_section_brands' %>

app/views/potepan/home/_new_products.html.erb
<div class="row featuredProducts">
  <div class="col-xs-12">
    <div class="page-header">
      <h4>新着商品</h4>
    </div>
  </div>
  <div class="col-xs-12">
    <div class="owl-carousel featuredProductsSlider">
      <% @new_products.each do |product| %>
        <div class="slide">
          <%= link_to potepan_product_path(product.id) do %>
            <div class="productImage clearfix">
              <%= image_tag(product.display_image.attachment(:large), :alt => "products-image") %>
            </div>
            <div class="productCaption clearfix">
              <h5><%= product.name %></h5>
              <h3><%= product.display_price %></h3>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/potepan/orders/_light_section.html.erb
<!-- LIGHT SECTION -->
<section class="lightSection clearfix pageHeaderImage">
  <div class="container">
    <div class="tableBlock">
      <div class="row tableInner">
        <div class="col-xs-12">
          <div class="page-title">
            <h2>cart</h2>
            <ol class="breadcrumb">
              <li>
                <a href="index.html">Home</a>
              </li>
              <li class="active">cart</li>
            </ol>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/potepan/orders/_line_item.html.erb
<%= order_form.fields_for :line_items, line_item do |line_item_fields| %>
  <tr>
    <td class="col-xs-2">
      <%= link_to potepan_line_item_path(line_item), class: "close", method: :delete do %>
        <span aria-hidden="true">&times;</span>
      <% end %>
      <span class="cartImage">
        <%= image_tag(line_item.variant.display_image.attachment(:small)) %>
      </span>
    </td>
    <td class="col-xs-4"><%= line_item.name %></td>
    <td class="col-xs-2"><%= line_item.display_price %></td>
    <td class="col-xs-2"><%= line_item_fields.number_field :quantity, min: 0 %></td>
    <td class="col-xs-2"><%= line_item.display_total %></td>
  </tr>
<% end %>

app/views/potepan/orders/edit.html.erb
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix cartListWrapper">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="cartListInner">
          <% if @order.line_items.empty? %>
            <p>カートは空です</p>
          <% else %>
            <%= render 'order_form', order: @order %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/potepan/products/_cart_form.html.erb
<%= form_for :order, url: potepan_line_items_path do |f| %>
  <% if product.variants.any? %>
    <span class='quick-drop'>
      <%= select_tag :variant_id, options_from_collection_for_select(product.varients, :id, :options_text), class: "select-drop" %>
    </span>
  <% else %>
    <%= hidden_field_tag "variant_id", @product.master.id %>
  <% end %>
  <span class="quick-drop resizeWidth">
    <%= select_tag :quantity, options_for_select([*1..5]), class: "select-drop" %>
  </span>
  <div class="btn-area">
    <%= button_tag(type: 'submit', class: 'btn btn-primary btn-block') do %>
      カートに入れる<i class="fa fa-angle-right" aria-hidden="true"></i>
    <% end %>
  </div>
<% end %>

app/views/potepan/products/_product_grid.html.erb
<% products.each do |product| %>
  <div class="col-sm-3 col-xs-12">
    <div class="productBox">
      <%= link_to potepan_product_path(product.id) do %>
        <div class="productImage clearfix">
          <%= image_tag(product.images.first ? product.images.first.url(:product) : Spree::Image.new.url(:product)) %>
        </div>
        <div class="productCaption clearfix">
          <h5><%= product.name %></h5>
          <h3><%= product.display_price%></h3>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/potepan/products/_related_products.html.erb
<div class="row productsContent">
  <div class="col-xs-12">
    <div class="page-header">
      <h4>関連商品</h4>
    </div>
  </div>
  <% related_products.each do |product| %>
    <div class="col-md-3 col-sm-6 col-xs-12">
      <div class="productBox">
        <%= link_to potepan_product_path(product.id) do %>
          <div class="productImage clearfix">
            <%= image_tag(product.display_image.attachment(:small)) %>
          </div>
          <div class="productCaption clearfix">
            <h5><%= product.name %></h5>
            <h3><%= product.display_price %></h3>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/potepan/products/search.html.erb
<%= provide :title, "Results by Search #{@search_word}" %>
<div class="main-wrapper">
  <section class="lightSection clearfix pageHeader">
    <div class="container">
      <div class="row">
        <div class="col-xs-6">
          <div class="page-title">
            <h2><%= @search_word %></h2>
          </div>
        </div>
        <div class="col-xs-6">
          <ol class="breadcrumb pull-right">
            <li>
              <%= link_to 'Home', potepan_index_path %>
            </li>
            <li>
              <%= link_to 'Shop', '#' %>
            </li>
            <li class="active">
              <%= @search_word %>
            </li>
          </ol>
        </div>
      </div>
    </div>
  </section>
  <section class="mainContent clearfix productsContent">
    <div class="container">
      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="row">
          <%= render 'product_grid', products: @products %>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/potepan/products/show.html.erb
<% provide(:title, @product.name) %>
<!-- LIGHT SECTION -->
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= @product.name %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <%= link_to("Home", potepan_index_url ) %>
          </li>
          <li class="active"><%= @product.name %></li>
        </ol>
      </div>
    </div>
  </div>
</section>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix">
  <div class="container">
    <div class="row singleProduct">
      <div class="col-xs-12">
        <div class="media">
          <%= render 'image', product: @product %>
          <div class="media-body">
            <ul class="list-inline">
              <li>
                <i class="fa fa-reply" aria-hidden="true">
                  <%= link_to("一覧ページへ戻る", potepan_category_path(@taxons.first.id)) %>
                </i>
              </li>
            </ul>
            <h2><%= @product.name %></h2>
            <h3><%= @product.display_price %></h3>
            <p><%= @product.description %></p>
            <span class="quick-drop">
              <select name="guiest_id3" id="guiest_id3" class="select-drop">
                <option value="0">S</option>
                <option value="1">M</option>
                <option value="2">L</option>
                <option value="3">XL</option>
              </select>
            </span>
            <%= render "cart_form", product: @product %>
          </div>
        </div>
      </div>
    </div>
    <%= render 'related_products', related_products: @related_products %>
  </div>
</section>